modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="l2backpack"
version="${file.jarVersion}" #mandatory
displayName="L2 Backpack" #mandatory
logoFile="l2backpack.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
'''
[[dependencies.l2backpack]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.51,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2backpack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2backpack]]
    modId="l2library"
    mandatory=true
    versionRange="[0.2.0,)"
    ordering="AFTER"