modLoader="javafml"
loaderVersion="[46,)"
license="LGPL v2.1"
[[mods]]
modId="l2backpack"
version="${file.jarVersion}" #mandatory
displayName="L2 Backpack" #mandatory
logoFile="l2backpack.png" #optional
credits="Thanks to ImprovedBackpack for QoL feature ideas" #optional
authors="lcy0x1 and LightLand team" #optional
description='''
Simple backpack mod that allows you to open backpack in player GUI or enderchest.
Also have some specialized bag for equipments, enchant books, and arrows.
'''
[[dependencies.l2backpack]]
    modId="forge"
    mandatory=true
    versionRange="[46.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2backpack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2backpack]]
    modId="l2library"
    mandatory=true
    versionRange="[2.4.0,)"
    ordering="AFTER"