modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
[[mods]]
modId="l2backpack"
version="${file.jarVersion}" #mandatory
displayName="L2 Backpack" #mandatory
logoFile="l2backpack.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
'''
[[dependencies.l2backpack]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.94,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2backpack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2backpack]]
    modId="l2library"
    mandatory=true
    versionRange="[1.5.0,)"
    ordering="AFTER"